version: '3.3'

volumes:
  postgres_data:
  static_data:
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: alexfofanov/api_yamdb:1.0
    restart: always
    volumes:
      - static_data:/code/static/
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000 # --access-logfile gunicorn_access.log
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_data:/usr/share/nginx/html/static
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
